# Generated by Django 5.2.11 on 2026-02-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='detection_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='event_videos/%Y/%m/%d/'),
        ),
    ]
