# Generated by Django 5.2.11 on 2026-02-06 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('feeds', '0001_initial'),
        ('situational_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='map_layouts/')),
                ('width_pixels', models.IntegerField()),
                ('height_pixels', models.IntegerField()),
                ('width_meters', models.FloatField(help_text='Physical width in meters')),
                ('height_meters', models.FloatField(help_text='Physical height in meters')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='MapObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_type', models.CharField(choices=[('wall', 'Wall'), ('door', 'Door'), ('camera', 'Camera'), ('nsg_unit', 'NSG Unit'), ('restricted_zone', 'Restricted Zone')], max_length=50)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('map_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='situational_map.maplayout')),
            ],
        ),
        migrations.CreateModel(
            name='SuspectPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.camerafeed')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
