# Generated by Django 5.2.11 on 2026-02-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situational_map', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapobject',
            name='obj_type',
            field=models.CharField(
                choices=[
                    ('wall', 'Wall'),
                    ('door', 'Door'),
                    ('camera', 'Camera'),
                    ('cctv', 'CCTV'),
                    ('nsg_unit', 'NSG Unit'),
                    ('restricted_zone', 'Restricted Zone'),
                    ('suspect', 'Suspect'),
                    ('police', 'Police'),
                    ('vip', 'VIP'),
                    ('gate', 'Gate'),
                    ('entry', 'Entry'),
                    ('exit', 'Exit'),
                ],
                max_length=50,
            ),
        ),
    ]
