# Generated by Django 5.2.11 on 2026-02-18 17:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('situational_map', '0003_mapobject_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayout',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='maplayout',
            name='name',
            field=models.CharField(default='Default Map', max_length=200),
        ),
        migrations.AddField(
            model_name='maplayout',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maplayout',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
        migrations.AlterField(
            model_name='maplayout',
            name='height_meters',
            field=models.FloatField(default=1.0, help_text='Physical height in meters'),
        ),
        migrations.AlterField(
            model_name='maplayout',
            name='width_meters',
            field=models.FloatField(default=1.0, help_text='Physical width in meters'),
        ),
    ]
