# Generated by Django 5.2.11 on 2026-02-06 18:30

import ai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceidentity',
            name='face_image',
            field=models.ImageField(upload_to=ai.models.face_identity_upload_path),
        ),
        migrations.AlterField(
            model_name='faceidentity',
            name='identity_type',
            field=models.CharField(choices=[('nsg', 'NSG Personnel'), ('police', 'Police Personnel'), ('suspect', 'Known Suspect'), ('unknown', 'Unknown')], max_length=20),
        ),
    ]
