# Generated by GitHub Copilot on 2026-02-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_faceidentity_face_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceidentity',
            name='identity_type',
            field=models.CharField(choices=[('nsg', 'NSG Personnel'), ('police', 'Police Personnel'), ('vip', 'VIP'), ('suspect', 'Known Suspect'), ('unknown', 'Unknown')], max_length=20),
        ),
        migrations.AddField(
            model_name='faceidentity',
            name='position',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='faceidentity',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
