# Generated by Django 5.2.11 on 2026-02-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_add_vip_and_face_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='model_type',
            field=models.CharField(choices=[('weapon_detection', 'Weapon Detection'), ('fire_smoke', 'Fire / Smoke Detection'), ('suspicious_behavior', 'Suspicious Behavior'), ('vehicle_detection', 'Vehicle Detection'), ('person_tracking', 'Person Tracking'), ('face_recognition', 'Face Recognition'), ('nsg_classification', 'NSG vs Non-NSG Classification'), ('fighting_violence_detection', 'Fighting / Violence Detection')], max_length=50),
        ),
    ]
